ibexa/http-cache

src/bundle/Resources/views/fields/content_fields.html.twig
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-538](https://issues.ibexa.co/browse/IBX-538)
| **Requires**                            | ibexa/core#13
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes
ibexa/core#13 updates `ibexa/core` Bundle names with proper Ibexa prefix instead of EzPublish. This PR aligns Twig namespace references with the bundle name change.
=> IBX-538: Replaced EzPublishCore Twig namespace references with IbexaCore

docs/extensibility.md, src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/IbexaHttpCacheExtension.php, src/bundle/IbexaHttpCacheBundle.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1589](https://issues.ibexa.co/browse/IBX-1589)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#5
- ~Provided automated test coverage.~ // full stack Behat coverage
=> IBX-1589: Renamed Extension ez_platform_http_cache to ibexa_http_cache

docs/drivers.md, src/bundle/DependencyInjection/Compiler/DriverPass.php, src/bundle/DependencyInjection/Compiler/ResponseTaggersPass.php, src/bundle/Resources/config/services.yml, src/bundle/Resources/config/view_cache.yml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
=> IBX-1694: Rebranded dependency injection container service tags

docs/drivers.md, docs/using_tags.md, spec/DependencyInjection/Compiler/KernelPassSpec.php, src/bundle/DependencyInjection/Compiler/DriverPass.php, src/bundle/DependencyInjection/Compiler/KernelPass.php, src/bundle/DependencyInjection/Compiler/VarnishCachePass.php, src/bundle/DependencyInjection/ConfigResolver/HttpCacheConfigParser.php, src/bundle/DependencyInjection/IbexaHttpCacheExtension.php, src/bundle/Resources/config/default_settings.yml, src/bundle/Resources/config/services.yml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
=> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

composer.json, features/setup/setup.feature, features/symfony/cache.feature, features/symfony/embed.feature
For some reason the tests are failing: https://github.com/ibexa/http-cache/runs/5035125358?check_suite_focus=true
```
In PrioritizedResourceManager.php line 70:
Can not find appropriate suite scope for class `Ibexa\Contracts\Core\SiteAc  
cess\ConfigResolverInterface`.     
```
because `  - Locking ibexa/core (v4.0.0-rc1)` is installed
I've changed it to `         "ibexa/core": "^4.0.x-dev",` so that correct ibexa/core version is used.
I've adjusted the regex so that it checks only the part that's needed (`fresh`) and is less prone to future rebranding changes.
=> [Behat] Adjusted pattern to rebranding

.github/pull_request_template.md, bootstrap.php, composer.json, docs/using_tags.md, spec/EventSubscriber/HiddenLocationExceptionSubscriberSpec.php, spec/EventSubscriber/HttpCacheResponseSubscriberSpec.php, spec/EventSubscriber/RestKernelViewSubscriberSpec.php, spec/EventSubscriber/XLocationIdResponseSubscriberSpec.php, spec/Handler/TagHandlerSpec.php, spec/ProxyClient/VarnishSpec.php, src/bundle/Resources/config/services.yml, src/lib/Twig/ContentTaggingExtension.php
=> IBX-1853: Used rebranded Ibexa name in codebase

src/bundle/Resources/config/default_settings.yml
| **JIRA issue**     | [IBX-5074](https://issues.ibexa.co/browse/IBX-5074)
| **Type**           | Bug
| **Target version** | 4.0
| **Doc needed**     | no
With the renaming from "ezplatform" to "ibexa", the "ibexa.http_cache.no_vary.routes" value was not fixed. Without this fix, all responses get Vary: cookie,authorization.
=> Fixed no_vary route name after rebranding

.github/workflows/ci.yaml
4.2 for reference:
https://github.com/ibexa/http-cache/blob/4.2/.github/workflows/ci.yaml#L76
This change should be reverted in main
=> [CI] Fixed invalid branch for 4.3 REST tests

src/contracts/Handler/ContentTagInterface.php
| **JIRA issue**     | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929)
| **Type**           | Bug
| **Target version** | 4.5
| **Doc needed**     | no
`Tag "since" with body "@since v0.9.3" has error`
- ~~Fix [`@since`](https://docs.phpdoc.org/3.3/guide/references/phpdoc/tags/since.html#since) usage (see https://github.com/ibexa/core/pull/226 for more)~~
- Remove the buggy tag
**TODO**:
=> IBX-4929: Fix PhpDoc

docs/varnish/vcl/varnish5.vcl, docs/varnish/vcl/varnish7.vcl
| **JIRA issue**     | [IBX-5854](https://issues.ibexa.co/browse/IBX-5854)
| **Type**           | Bug
| **Target version** | `4.5`
| **Doc needed**     | yes? (VLCs needs to be changed on update procedure)
**TODO**:
=> IBX-5854: Allowed cookies prefixed with `ibexa-`

features/setup/setup.feature, features/symfony/cache.feature, features/symfony/embed.feature, features/symfony/permissions.feature, features/varnish/cache.feature, features/varnish/embed.feature, features/varnish/permissions.feature, features/varnish/translations.feature
| **JIRA issue**     | [IBX-7409](https://issues.ibexa.co/browse/IBX-7409)
| **Type**           | Improvement
| **Target version** | latest stable `4.6` for bug fixes, `main` for new features
| **Doc needed**     | no
Changed Content Type to content type
**TODO**:
=> IBX-7409: Changed Content Type to content type

src/contracts/Handler/ContentTagInterface.php
| **JIRA issue**     | [IBX-XXXXX](https://issues.ibexa.co/browse/IBX-XXXXX)
| **Type**           | Bug/Improvement/Feature/Misc
| **Target version** | latest stable `4.0` for bug fixes, `main` for new features
| **BC breaks**      | yes/no
| **Doc needed**     | yes/no
`ContentTagInterface`: fix [`@see`](https://docs.phpdoc.org/guide/references/phpdoc/tags/see.html) usage to avoid error
`Tag "see" with body "@see "docs/using_tags.md"" has error "\Ibexa\Contracts\HttpCache\Handler\"docs/using_tags.md"" is not a valid Fqsen.`
**TODO**:
=> Fixes PhpDoc

composer.json
| **JIRA issue**     | N/A
| **Type**           | Improvement
| **Target version** |`4.6` 
| **Doc needed**     | no
The section `autoload-dev` was duplicated.
```
Key autoload-dev is a duplicate in ./composer.json at line 61
```
**TODO**:
=> Fixed composer.json file

src/bundle/Resources/views/fields/content_fields.html.twig
| :ticket: Issue | IBX-9513 |
- https://github.com/ibexa/core/pull/474
- https://github.com/ibexa/fieldtype-query/pull/35
Fixed single colon controller references, which seem to be no longer working in Symfony 6.
Note: we have behat failures for http cache fetatures and REST integration tests failures, which need to be handled separately.
The bug might be reproducible in a similar form to the one from JIRA ticket, when using HTTP cache (e.g. Varnish). Not 100% sure however, just a guess. If so, affected field types:
* Relation
* Relation List
* Image Asset
=> IBX-9513: Fixed obsolete `ibexa_content` Controller references

.github/workflows/ci.yaml, composer.json, rector.php, src/lib/Twig/ContentTaggingExtension.php
| :ticket: Issue | IBX-9584 |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [PHP] Updated method reference syntax
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+. 
Sanities.
N/A
=> IBX-9584: Resolved Symfony 6.x deprecations

src/bundle/Resources/views/fields/content_fields.html.twig
| :ticket: Issue | N/A       |
> The spaceless filter is deprecated as of Twig 3.12 and will be removed in Twig 4.0.
See https://twig.symfony.com/doc/3.x/deprecated.html 
Limitations and field types rendering.
N/A
=> [Twig] Removed usage of deprecated spaceless filter

features/symfony/cache.feature, features/symfony/embed.feature, features/symfony/permissions.feature, features/varnish/cache.feature, features/varnish/embed.feature, features/varnish/permissions.feature, features/varnish/translations.feature, src/bundle/Resources/config/routing.yml
| :ticket: Issue | IBX-XXXXX |
=> [CI] Normalized expected headers names to lowercase

src/lib/Handler/TagHandler.php
| :ticket: Issue | IBX-XXXXX |
Follow up for https://github.com/ibexa/http-cache/pull/63.
Issue detected by https://github.com/ibexa/fieldtype-page/actions/runs/14773790369/job/41478333517
```
│  	[2025-05-01T10:26:13.389330+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Ibexa\HttpCache\Handler\TagHandler::Ibexa\HttpCache\Handler\{closure}(): Argument #1 ($locationId) must be of type string, null given" at TagHandler.php line 137 {"exception":"[object] (TypeError(code: 0): Ibexa\\HttpCache\\Handler\\TagHandler::Ibexa\\HttpCache\\Handler\\{closure}(): Argument #1 ($locationId) must be of type string, null given at /var/www/vendor/ibexa/http-cache/src/lib/Handler/TagHandler.php:137)"} []
```
N/A
N/A
=> Refactored tag handling methods to support numerical ids

.github/workflows/ci.yaml, composer.json, ignore-by-php-version.neon.php, ignore-gte-php8.0-errors.neon, ignore-php7.4-errors.neon, phpstan-baseline.neon, phpstan.neon.dist
| :ticket: Issue | N/A      |
Added phpstan configuration and initialized baseline. 
N/A
N/A
=> Added phpstan configuration

.github/workflows/browser-tests.yaml, .github/workflows/ci.yaml, composer.json
=> [CI] Aligned secrets
